// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adg/scrip": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "verifies the JWT and adds/ deletes/ gets the scrip in the request to/ from the list of watchlists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watchlist"
                ],
                "summary": "Perform ADG for watchlist",
                "parameters": [
                    {
                        "description": "ADG Watchlist Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BffAdgStoWatchlistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ADG Performed successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BffAdgStoWatchlistResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "401": {
                        "description": "Case A: JWT expired / Case B: JWT invalid / Case C: Unauthorized request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "404": {
                        "description": "User does not exist",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Actiontype": {
            "type": "string",
            "enum": [
                "ADD",
                "DEL",
                "GET"
            ],
            "x-enum-varnames": [
                "AddAction",
                "DelAction",
                "GetAction"
            ]
        },
        "models.BffAdgStoWatchlistRequest": {
            "type": "object",
            "required": [
                "action",
                "scripId"
            ],
            "properties": {
                "action": {
                    "description": "ADD or  DEL or GET",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Actiontype"
                        }
                    ],
                    "example": "GET"
                },
                "scripId": {
                    "type": "string",
                    "example": "RELI_2018"
                },
                "watchlistIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "models.BffAdgStoWatchlistResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "the one from the request",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Actiontype"
                        }
                    ]
                },
                "status": {
                    "description": "success or failure, if succeded - descriptive message, if failed - failed adding/ deleting/ getting scrip to wathclist...",
                    "type": "string"
                },
                "warnings": {
                    "description": "only while adding if a scrip already exists in a watchlist",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "watchlistNames": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WatchlistWithId"
                    }
                }
            }
        },
        "models.ErrorAPIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "$ref": "#/definitions/models.ErrorMessage"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "models.WatchlistWithId": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "x-extension-openapi": "{\"example\": \"value on a json format\"}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Watchlists ADG Service API",
	Description:      "Watchlists ADD DEL GET APIs for Stock Broker Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
